# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm
    - name: install dependencies
      run: pnpm install --frozen-lockfile

    - run: pnpm lint

    - run: pnpm build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: sites/maplibre-gl-area-switcher.water-gis.com/dist # The folder the action should deploy.
